targets = [
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "x86_64-unknown-linux-gnu" },
]

[licenses]
unlicensed = "deny"
allow = [
    #"MIT",
    "Apache-2.0",
    #"Apache-2.0 WITH LLVM-exception",
]

[bans]
multiple-versions = "deny"
wildcards = "allow"
deny = []

skip-tree = [
]
